project:
  type: website
  output-dir: docs

filters:
- nceas-learning-hub/lh_theme
exercises: ### for custom theme callouts
  number: false ### see https://cambiotraining.github.io/quarto-course-template/materials/02-content_guidelines.html but does not work
editor: source
bibliography: book.bib

format:
  html:
    theme:
       light: _extensions/nceas-learning-hub/lh_theme/lh_light.scss
       dark: _extensions/nceas-learning-hub/lh_theme/lh_dark.scss
    css: _extensions/nceas-learning-hub/lh_theme/lh_style.css
      ### doesn't render NCEAS logo if put in scss file?
      ### seems to work locally but not when published on GitHub
    toc: true
    number-sections: true
    title-block-banner: "blue" ### need this here to "turn on" the title-block-banner

website:
  title: "COURSE_TITLE (COURSE_DATES)"
  reader-mode: false
  repo-url: COURSE_REPO

  favicon: _extensions/nceas-learning-hub/lh_theme/logo_lh_hex.png # learning hub logo on browser tab

  bread-crumbs: false
  navbar:
    right:
      - text: "Instructors"
        menu:
          - text: "Casey O'Hara"
            href: https://www.oharascience.com/
      - icon: github
        href: COURSE_REPO
        aria-label: GitHub

  sidebar:
    title: "Training Materials"
    style: "floating"
    search: true
    tools:
      - icon: house-door-fill
        href: https://www.nceas.ucsb.edu/learning-hub
      - icon: twitter
        href: https://twitter.com/ucsb_nceas
      - icon: github
        href: COURSE_URL
    contents:
      - index.qmd # preface
      SESSION_LINKS

  page-footer:
    center: "Copyright \u00a9 2024, NCEAS"
    ### NCEAS main website footer:
    # center: "\u00a9 The Regents of the University of California, All Rights Reserved"
    # could also include license info?


